Universe       = vanilla
# Requirements   = Machine == "mc3.lcc.uma.es"
RequestCPUs    = 1
Request_memory = 1G
Executable     = autorun.sh
Arguments      = "60 $(Process)"
Output         = logs/output.$(Process).out
Error          = logs/error.$(Process).err
Log            = logs/log.$(Process).log
Should_transfer_files   = YES
Transfer_input_files    = worker-app.zip
When_to_transfer_output = ON_EXIT
Queue 1
